name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write


    strategy:
      matrix:
        goos: [windows, darwin, linux]
        goarch: [amd64]

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Build
      run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o zaicmd-${{ matrix.goos }}-${{ matrix.goarch }}

    - name: Compress artifact
      run: tar -czvf zaicmd-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz zaicmd-${{ matrix.goos }}-${{ matrix.goarch }}

    - name: Upload Release Asset
      uses: actions/upload-artifact@v4
      with:
        name: zaicmd-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
        path: zaicmd-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./downloads

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.CR_PAT}}
      with:
        files: |
          ./downloads/**

